name: cppcheck

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Linux-cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cppcheck
      uses: chmorgan/cppcheck-action-jackson@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        enable: all
        force_language: c++
        std: c++20
        platform: unix64
        other_options: --bug-hunting -I inc/ --verbose --suppress=missingIncludeSystem --enable=warning
      
    #- name: publish report    
    #  uses: mikeal/publish-to-github-action@master
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    BRANCH_NAME: 'main'
