name: cppcheck

on:
  push:
  pull_request:

jobs:
  Linux-cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: chmorgan/cppcheck-action-jackson@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          enable: all
          inconclusive: enable
          inline_suppression: enable
          force_language: c++
          platform: unix64
          std: c++20
          output_file: cppcheck_output.txt
          other_options: -I inc --file-filter=*cppsocket* --verbose --suppress=missingIncludeSystem
