name: cppcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
    
permissions:
    actions: write
    contents: write

jobs:
  Linux-cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: tonybaloney/cppcheck-action@master
        with:
          opts: --enable=all -I inc --verbose --suppress=missingIncludeSystem --platform=unix64 --inline-suppr --std=c++20
