name: cppcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  Linux-cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Bedzior/run-cppcheck@v1.0.0
        with:
          include directories: inc
          path: test
          verbose: true

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: output
