name: cppcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  Linux-cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: testing
        run: ls -lat && pwd

      - uses: tonybaloney/cppcheck-action@master
        with:
          opts: --enable=all -I inc --verbose --suppress=missingIncludeSystem --platform=unix64 --inline-suppr --std=c++20
          path: test
