name: cppcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cppcheck hpp
      run: |
        cppcheck -v --bug-hunting --enable=all --language=c++ --platform=unix64 --std=c++20 inc/cppsocket.hpp
        cppcheck -v --bug-hunting --enable=all --language=c++ --platform=unix64 --std=c++20 test/TestCppSocket.cpp


